### ISSUE TITLE
integrate travis ci

### ISSUE THREAD

**Issue by tomatophantastico** [Iranox/bsbmloader-docker#20]
create a travis ci account
add .travis.yml
test if the docker-compose up and test-data loading mit 100 produkten funktioniert
integration test

**Comment by tomatophantastico** [comment]
this might help
https://elliot.land/using-docker-compose-on-travis-ci

**Comment by Iranox** [comment]
45527a4 adds a simple travis.yml. It runs docker-compose up and docker-compose stop.
