### ISSUE TITLE
transition to docker networking

### ISSUE THREAD

**Issue by tomatophantastico** [Iranox/bsbmloader-docker#28]
instead of linking containers, use docker networking

**Comment by tomatophantastico** [comment]
remove all links between containers, use the hostname/servicename instead, like: 
jdbc:mysql:mysqlhostname:3307/testdb (most likely)

**Comment by tomatophantastico** [comment]
check if links are necessary in mongodb_horizontal_shard scenario

**Comment by Iranox** [comment]
Update dockerfiles to v2. All links were removed. See  15587ca
